version: "2.1"

services:

  duckdns:
    image: linuxserver/duckdns
    container_name: duckdns
    environment:
      - PUID=1000 #optional
      - PGID=984 #optional
      - TZ=${TIMEZONE}
      - SUBDOMAINS=${SUBDOMAINS}
      - TOKEN=${DUCKDNS_TOKEN}
      - LOG_FILE=false #optional
    volumes:
      - ${CLIENT_PATH}:/config #optional
    restart: always
    networks:
      net:

networks:
  net: